### ISSUE TITLE
如何创建一个群组内共享人格的bot, 以及删除回复后面的建议回复信息

### ISSUE THREAD

**Issue by KiDisplayBlueScreen** [canxin121/nonebot_poe_chat#2]
如题. 我想让一个群里所有人都用我创建的人格, 省得每次有人聊天的时候都要新建人格
另外后面的建议回复可以删除吗
![image](https://user-images.githubusercontent.com/33929772/234569265-b7bc4c14-c342-4018-8cb9-4f8a6da8db47.png)

**Comment by canxin121** [comment]
指的是每次自动创建的预设由你指定是吧，这个很好做，下次更新加上。还有建议回复的开关我已经在api做了接口，只不过还没在插件写完，下次更新就会有这个配置选项

**Comment by KiDisplayBlueScreen** [comment]
> 指的是每次自动创建的预设由你指定是吧，这个很好做，下次更新加上。还有建议回复的开关我已经在api做了接口，只不过还没在插件写完，下次更新就会有这个配置选项

应该是直接用已有的预设吧 每次自动创建的话自己的poe上bot不是会越来越多吗

**Comment by canxin121** [comment]
就是让poe上的bot越来越多，因为要保证每个人的对话都是单独的，否则会互相干扰，无法正常使用。如果你想所有人共享一个bot的话，请直接用共享的gpt或者claude，所谓预设你直接发给他就行了，清空对话就清除了预设，再重新发预设就可以了。还有自动创建gpt时的预设已经可以由管理员实时修改了。

**Comment by KiDisplayBlueScreen** [comment]
> 

啊，，那poe平台会有限制的吧

**Comment by canxin121** [comment]
暂时没发现有限制，我已经建了非常多了，这个所谓机器人其实就是一个新会话窗口而已，就和你在openai新开一个对话一样
