### ISSUE TITLE
开启以图片形式发送后无法正常回复

### ISSUE THREAD

**Issue by EnchantedHay** [canxin121/nonebot_poe_chat#3]
[WARNING] nonebot_plugin_gocqhttp | [100000000] 警告: 群 70000000 图片上传失败: upload failed: highway upload error: failed to read byte: read tcp 10.7.75.189:55745->220.194.118.239:8080: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

（机器人QQ号和群号已处理）
报错如上。代理使用Clash系统代理，.env未配置poe_server。

**Comment by canxin121** [comment]
这个可能不是本插件的问题，是gocqhttp报的错，应该是你的网络延迟过高，可以看下自己是不是搞成全局代理走国外了，或者分流分错了？可以先试试其他发送大图片的插件能否使用，排除一下。

**Comment by EnchantedHay** [comment]
是的，使用的是全局代理，主要是不用Global用Rule的话无法访问poe.com...那么或许是不是只好用文字发送了

**Comment by canxin121** [comment]
事实上你应该把clash配置好，推荐使用clash verge客户端，并使用 https://acl4ssr-sub.github.io/ 这个网站或者其他，将你的订阅链接转换成分流完善的配置文件，然后直接规则分流即可

**Comment by EnchantedHay** [comment]
> 

好的，谢谢您。
