### ISSUE TITLE
(没有正确设置配置项造成)普通用户无法使用指令提问，只能superuser使用

### ISSUE THREAD

**Issue by ABKQPO** [canxin121/nonebot_poe_chat#8]
请问最新的配置项有哪些，是不是gpt4的改错了

**Comment by canxin121** [comment]
详细配置请看文档库[特权用户名单](https://canxin121.github.io/docs/docs/nonebot-poe-chat.html#%E7%89%B9%E6%9D%83%E7%94%A8%E6%88%B7%E5%90%8D%E5%8D%95)，gpt4和claude+只有特权用户列表内的用户或群聊可以使用(比较珍贵)，默认特权用户是superuser，如果还不可以的话，我再看看

**Comment by ABKQPO** [comment]
那可以再加个指定bot的文字或图片输出的功能吗

**Comment by canxin121** [comment]
后面会加丰富的自定义，不过得等重够完代码，彻底更改原来的数据结构，估计是另一个项目了，因为目的是兼容多来源多平台，你可以等一等
