### ISSUE TITLE
创建机器人失败, 是否应该添加日志输出

### ISSUE THREAD

**Issue by KiDisplayBlueScreen** [canxin121/nonebot_poe_chat#9]
今天突然开始创建机器人失败, 但控制台又没有失败的原因

**Comment by canxin121** [comment]
已修复，是poe更新引起，请更新即可使用

**Comment by canxin121** [comment]
日志应该没啥用，debug一下直接就能看出来，毕竟只是playwright，代码过程很简单

**Comment by KiDisplayBlueScreen** [comment]
> 已修复，是poe更新引起，请更新即可使用
好 还有个问题是你这预设是默认用UTF8保存的吗？我用英文写的预设无法起作用

**Comment by canxin121** [comment]
应该是utf-8，是用命令添加的吗？还是手动写进去的？

**Comment by KiDisplayBlueScreen** [comment]
> 应该是utf-8，是用命令添加的吗？还是手动写进去的？

命令添加 我改用中文也不行 pcp切换自己创建的预设之后还是默认的预设

**Comment by canxin121** [comment]
应该是你写的预设不够强力，gpt3.5没有吃进去，建议网上找点有效的预设

**Comment by KiDisplayBlueScreen** [comment]
> 应该是你写的预设不够强力，gpt3.5没有吃进去，建议网上找点有效的预设

我看了机器人的prompt是空的

**Comment by canxin121** [comment]
呃呃，加群，qq说一下吧，发下你预设

**Comment by canxin121** [comment]
我刚才重新安装，删了所有配置试过了，我这里正常
